<?xml version="1.0" encoding="UTF-8"?><testrun name="TestMemberService" project="MyCoach" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="TestMemberService" time="2.167">
    <testcase name="testAddMember" classname="TestMemberService" time="2.167">
      <error>org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [insert into member (email, password) values (?,?)]; SQL state [HY000]; error code [1366]; Incorrect integer value: 'ravi@gmail.com' for column 'email' at row 1; nested exception is java.sql.SQLException: Incorrect integer value: 'ravi@gmail.com' for column 'email' at row 1&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:605)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:818)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:874)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:882)&#13;
	at com.cog.repo.MemberRepository.addMember(MemberRepository.java:24)&#13;
	at com.cog.service.MemberService.addMember(MemberService.java:17)&#13;
	at TestMemberService.testAddMember(TestMemberService.java:29)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.sql.SQLException: Incorrect integer value: 'ravi@gmail.com' for column 'email' at row 1&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)&#13;
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)&#13;
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)&#13;
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)&#13;
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)&#13;
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)&#13;
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)&#13;
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)&#13;
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:824)&#13;
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:818)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:589)&#13;
	... 34 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
